### ISSUE TITLE
Error while fetching brawler icon [KeyError: '16000056']

### ISSUE THREAD

**Issue by masawik** [PyStarr/BrawlPy#2]
this is the best library for working with the brawlstars API of all that I found on github 👍
But please delete the icon fetching if you don't want to constantly monitor the release of new brawlers.

> 😣
Traceback (most recent call last):
  File "main.py", line 9, in main
    player = await client.get_player("9GR8GCQYR")
  File "venv\lib\site-packages\brawlpy\main.py", line 63, in get_player
    br = PlayerBrawler(each['name'],each['id'],each['power'],each['rank'],each['trophies'],each['highestTrophies'],grs,gears,srs)
  File "venv\lib\site-packages\brawlpy\objects.py", line 271, in __init__
    self.icon_id = self.get_icon_url()
  File "venv\lib\site-packages\brawlpy\objects.py", line 288, in get_icon_url
    return br_icons[str(self.id)]
KeyError: '16000056'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000028C930C72B0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000028C93C3EBA8>, 18250.187)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000028C930C7E80>
Process finished with exit code 1

### ✅ Monkey solution ✅
If you are facing the same problem and the use of icons is not important to you, then just replace it
`return br_icons[str(self.id)]`
with this
`return br_icons["16000000"]`

on lines `250` and `287` in your `venv/Lib/site-packages/brawlpy/objects.py` file.
In this case, the _shelly_ icon will always be used.

**Comment by yxshv** [comment]
omaigat someone using it

**Comment by yxshv** [comment]
ok i am deleting it

**Comment by yxshv** [comment]
thanks for using the api

**Comment by yxshv** [comment]
install the developement version

**Comment by yxshv** [comment]
done
