### ISSUE TITLE
It's supports slash commands?

### ISSUE THREAD

**Issue by AstroicyOP** [PyStarr/BrawlPy#3]

**Comment by yxshv** [comment]
what commands? do you mean discord slash commands?

**Comment by kubune** [comment]
It's just a library to get brawl stars info from its API

First connect the api key with
`client = brawlpy.Client('your api key')`

Then, initialize slash command and before giving info to user, parse the info the command should do into the api and get it to variable. After that do whatever you want like a regular slash command...

It's really not that hard tbh
